[package]
name = "two-sided-vec"
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]

[dependencies]
serde = { version = "^1.0.27", optional = true }

[dev-dependencies]
serde_test = { version = "^1" }